# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08e1e17fe0061f0d7c3f6c82224f326eb60286482c3acc485f5944db10de6ab4270f9449b0cf82f3c8d43fa3d7a3925ca56c503bb4d8f0363ddc8c0cff518491

test:
  secret_key_base: c8dcc4432e105e11d45949ce3cd9cda43821ee566b08dbac240c6fd606a7b640be94a8ea1ff49d4fe10abd0fbfb37c6dad0a46cb5b967793f49578ebbcc4fe04

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
